language: node_js
sudo: true
dist: trusty
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
before_script:
  - npm run lint
script:
  - xvfb-run npm run coverage
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
